### ISSUE TITLE
如何使用GPU加速训练和计算大语料的句子相似度？

### ISSUE THREAD

**Issue by i-wanna-to** [MachineLP/TextMatch#9]
大佬你好！你的这个项目很不错！我这里有个小问题，希望得到你的帮助。

我已经跑通了bert和albert的训练文件(train_model文件夹下的train_bert.py和train_albert.py)，但是我发现训练和测试的时候都是使用的cpu。如果我想用GPU进行训练和测试需要做什么修改呢？谢谢！

**Comment by MachineLP** [comment]
> 大佬你好！你的这个项目很不错！我这里有个小问题，希望得到你的帮助。
> 
> 我已经跑通了bert和albert的训练文件(train_model文件夹下的train_bert.py和train_albert.py)，但是我发现训练和测试的时候都是使用的cpu。如果我想用GPU进行训练和测试需要做什么修改呢？谢谢！

我初步猜测你是安装的 cpu版本的tensorflow；pip list看一下是 tensorflow 还是 tensorflow-gpu；安装gpu版本的tensorflow需要pip install tensorflow-gpu

**Comment by i-wanna-to** [comment]
哈哈，谢谢大佬。应该是这个问题。只是项目需要的tensorflow版本有点低了，导致和现在cuDNN版本不兼容。那我关了issue了。
